const PDFDocument = require("pdfkit");

const translations = {
  en: {
    title: "Referral Slip",
    name: "Patient Name",
    age: "Age",
    symptoms: "Symptoms",
    urgency: "Urgency",
    facility: "Recommended Facility",
    footer: "Generated by MediConnect Rural",
  },

  hi: {
    title: "रेफरल पर्ची",
    name: "रोगी का नाम",
    age: "आयु",
    symptoms: "लक्षण",
    urgency: "गंभीरता",
    facility: "अनुशंसित स्वास्थ्य केंद्र",
    footer: "मेडीकनेक्ट ग्रामीण द्वारा तैयार",
  },
};

function generateReferralPDF(data, res) {
  const doc = new PDFDocument({ margin: 50 });

  const lang = data.language || "en";
  const t = translations[lang];

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    "attachment; filename=referral.pdf"
  );

  doc.pipe(res);

  doc.fontSize(22).text(t.title, {
    align: "center",
  });

  doc.moveDown();

  doc.fontSize(14).text(`${t.name}: ${data.name}`);
  doc.text(`${t.age}: ${data.age}`);
  doc.text(`${t.symptoms}: ${data.symptoms}`);
  doc.text(`${t.urgency}: ${data.urgency}`);
  doc.text(`${t.facility}: ${data.facility}`);

  doc.moveDown();

  doc.text(t.footer);

  doc.end();
}

module.exports = generateReferralPDF;